### ISSUE TITLE
cache doesn't work.

### ISSUE THREAD

**Issue by fengxsong** [gin-contrib/cache#1]
Hello, I have some problem when i used this middleware.
Both `SiteCache` and `CachePage`  will never hit the cache.
I think the reason is the `cachedWriter.Write` function does not executed.

**Comment by appleboy** [comment]
Please provide your code. Thanks.

**Comment by fengxsong** [comment]
@appleboy You can try the your [example][1].

In `CachePage`, `persistence.CacheStore.Get` always return an error(ErrCacheMiss)

[1]: https://github.com/gin-contrib/cache/blob/master/example/example.go

**Comment by dstroot** [comment]
I can confirm this error.

**Comment by dstroot** [comment]
Pulling the package also brings godeps and godeps is pointing to github not gopkg - causes errors

**Comment by easonlin404** [comment]
@fengxsong @dstroot I had checked this issue. Because `c.String` func called `ResponseWriter.WriteString` internal and cachedWriter doesn't implement it.  PR https://github.com/gin-contrib/cache/pull/5
