### ISSUE TITLE
Cache containing data multiple time

### ISSUE THREAD

**Issue by Sata51** [gin-contrib/cache#15]
After 12 day in production without any problem. I received a strange response from a cached route.

By default my response is a JSON Object like this:
```javascript
{
     "data":{}
}
```

In my case cached response look like this:
```javascript
{
     "data":{}
}{
     "data":{}
}{
     "data":{}
}
```

This result as a non parseable JSON.

Is it a problem with concurrency, how to avoid this ? 
Is there an implementation solution to avoid multiple concurrent call to be cached in the same time ?

Thanks

**Comment by gabstv** [comment]
It definitely looks like a concurrency issue. I have the same need of an atomically cached page, maybe like:  
```Go
func CachePageAtomic(store persistence.CacheStore, expire time.Duration, handle gin.HandlerFunc) gin.HandlerFunc { /* ... */ }
```
