### ISSUE TITLE
v1.1.0 using unmaintained redigo version

### ISSUE THREAD

**Issue by Hanggi** [gin-contrib/cache#78]
```
go get github.com/gin-contrib/cache
go: warning: github.com/gomodule/redigo@v2.0.0+incompatible: retracted by module author: Old development version not maintained or published.
```
https://github.com/gin-contrib/cache/blob/v1.1.0/go.mod#L9

Could you please update go.mod version to master version?

**Comment by thinkerou** [comment]
@Hanggi the latest version of redigo is v1.8.9, https://github.com/gomodule/redigo/releases, v2.0.0 published on 2018 https://github.com/gomodule/redigo/releases/tag/v2.0.0

so, the issue is not gin. thanks!

**Comment by Hanggi** [comment]
The latest version solve the issue.

Thank you very much!
