### ISSUE TITLE
gopkg url?

### ISSUE THREAD

**Issue by aequasi** [gin-contrib/cache#8]
kind of a newbie to this golang and gopkg stuff, but im using gin with `gopkg.in/gin-gonic/gin.v1`, and it wont let me use this package (types conflict...)

```
cannot use "github.com/gin-contrib/cache".CachePage(store, time.Second * 10, Search) (type "github.com/gin-gonic/gin".HandlerFunc) as type "github.com/aequasi/search.discordservers.com/vendor/gopkg.in/gin-gonic/gin.v1".HandlerFunc in argument to r.RouterGroup.GET
```

**Comment by easonlin404** [comment]
Please don't use `gopkg.in/gin-gonic/gin.v1` , use like https://github.com/gin-gonic/gin#use-a-vendor-tool-like-govendor to get stable v1.2. or get latest version:
```
go get github.com/gin-gonic/gin
```

**Comment by chetansurwade** [comment]
Kindly make a new release of this package, can not use dep for package management due to conflicting dependencies of different sources. i.e. an import of gin-gonic/gin.v1 in your release 1.0 cache.go

**Comment by appleboy** [comment]
@chetansurwade bump to https://github.com/gin-contrib/cache/releases/tag/v1.1.0

**Comment by chetansurwade** [comment]
@appleboy thanks a lot
